## Step 1 : Load The Dataset 


In this lab, you'll work with a realistic weather dataset. You'll use **Pandas** to explore and clean the data, and **NumPy** to perform matrix operations.

**Dataset:** `hourly_weather_10_days.csv` (10 days of hourly weather data)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('hourly_weather_10_days.csv')

In [3]:
df.head()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3
2,2023-03-01 02:00:00,15.3,73.3,4.7,NaN,11.1
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8

## Ste 2 : Basic Exploration 

Check column names and data types

Display basic statistics using .describe()

Count missing values in each column

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        240 non-null    object
 1   temperature_C    228 non-null    float64
 2   humidity_%       224 non-null    float64
 3   wind_speed_kmph  226 non-null    float64
 4   pressure_hPa     223 non-null    float64
 5   visibility_km    228 non-null    float64
dtypes: float64(5), object(1)
memory usage: 11.4+ KB
None

In [5]:
df.describe()

       temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
count     228.000000  224.000000       226.000000    223.000000     228.000000
mean       21.315789   66.795982        10.105310   1011.884753       9.989474
std         3.421237    8.190300         3.940668      5.187080       1.022166
min        11.500000   47.800000         1.300000    998.100000       6.800000
25%        18.700000   61.075000         6.625000   1008.900000       9.275000
50%        21.900000   66.300000         9.800000   1012.100000      10.000000
75%        23.925000   72.725000        13.500000   1015.100000      10.700000
max        28.700000   88.100000        17.800000   1027.000000      12.600000

In [6]:
df.isna().sum()

timestamp           0
temperature_C      12
humidity_%         16
wind_speed_kmph    14
pressure_hPa       17
visibility_km      12
dtype: int64

In [7]:
df.columns

Index(['timestamp', 'temperature_C', 'humidity_%', 'wind_speed_kmph',
       'pressure_hPa', 'visibility_km'],
      dtype='object')

In [8]:
df.isnull().sum() / len(df) * 100

timestamp          0.000000
temperature_C      5.000000
humidity_%         6.666667
wind_speed_kmph    5.833333
pressure_hPa       7.083333
visibility_km      5.000000
dtype: float64

## Step 3 : Handle Missing Values

Drop of fill missing values

Justify your approach (e.g, fill with mean, forward fill, etc.)

In [9]:
df[df['temperature_C'].isnull()]

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
10,2023-03-01 10:00:00,NaN,66.3,13.5,1013.7,11.5
41,2023-03-02 17:00:00,NaN,67.6,NaN,1009.5,10.0
65,2023-03-03 17:00:00,NaN,58.5,12.7,1015.0,10.1
84,2023-03-04 12:00:00,NaN,54.8,15.9,1012.7,9.6
105,2023-03-05 09:00:00,NaN,60.6,15.6,1008.8,9.0
147,2023-03-07 03:00:00,NaN,73.3,8.6,1008.6,10.5
169,2023-03-08 01:00:00,NaN,83.3,5.2,1005.1,9.1
178,2023-03-08 10:00:00,NaN,62.8,16.9,1009.3,9.3
181,2023-03-08 13:00:00,NaN,63.8,15.2,1002.7,11.3
206,2023-03-09 14:00:00,NaN,64.9,12.2,1012.7,11.9
228,2023-03-10 12:00:00,NaN,47.8,17.0,1013.8,11.4
237,2023-03-10 21:00:00,NaN,71.4,4.5,1001.7,10.7

In [10]:
df.ffill(inplace=True)

In [11]:
df.isna().sum()

timestamp          0
temperature_C      0
humidity_%         0
wind_speed_kmph    0
pressure_hPa       0
visibility_km      0
dtype: int64

## Step 4 : Data Analysis

Calculate daily average temperature

Find max, min, mean for each metric

Which hour of the day is the most humid on average?

In [12]:
# pd.to_datetime() is a pandas function whose sole purpose is to convert something that looks like a date/time but isn't recognized as one, 
# into a proper datetime object that pandas can understand and work with. 

# Converting timestamp to datetime type 
df['timestamp'] = pd.to_datetime(df['timestamp']) 

# Extracting date : 
df['date'] = df['timestamp'].dt.date

In [13]:
df['date']

0      2023-03-01
1      2023-03-01
2      2023-03-01
3      2023-03-01
4      2023-03-01
          ...
235    2023-03-10
236    2023-03-10
237    2023-03-10
238    2023-03-10
239    2023-03-10
Name: date, Length: 240, dtype: object

In [14]:
"From the dataframe, group all rows by date, then from each group pick only the temperature column, then calculate the mean — and store the result."
daily_avg_temp = df.groupby('date')['temperature_C'].mean()

In [15]:
print(daily_avg_temp)

date
2023-03-01    21.550000
2023-03-02    21.366667
2023-03-03    21.433333
2023-03-04    21.554167
2023-03-05    21.670833
2023-03-06    21.858333
2023-03-07    21.037500
2023-03-08    20.762500
2023-03-09    20.945833
2023-03-10    21.716667
Name: temperature_C, dtype: float64

In [16]:
# Extracting Hour from the timstamp column : 

df['hour'] = df['timestamp'].dt.hour

In [17]:
df['hour']

0       0
1       1
2       2
3       3
4       4
       ..
235    19
236    20
237    21
238    22
239    23
Name: hour, Length: 240, dtype: int32

In [18]:
# Finding the most humid hour on avg :

df.groupby('hour')['humidity_%'].mean().max()

78.41999999999999

In [19]:
df.head()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km,date,hour
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5,2023-03-01,0
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3,2023-03-01,1
2,2023-03-01 02:00:00,15.3,73.3,4.7,1012.1,11.1,2023-03-01,2
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9,2023-03-01,3
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8,2023-03-01,4

In [20]:
df['time'] = df['timestamp'].dt.time

In [21]:
df['time']

0      00:00:00
1      01:00:00
2      02:00:00
3      03:00:00
4      04:00:00
         ...
235    19:00:00
236    20:00:00
237    21:00:00
238    22:00:00
239    23:00:00
Name: time, Length: 240, dtype: object

In [22]:
df.head()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km,date,hour,time
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5,2023-03-01,0,00:00:00
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3,2023-03-01,1,01:00:00
2,2023-03-01 02:00:00,15.3,73.3,4.7,1012.1,11.1,2023-03-01,2,02:00:00
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9,2023-03-01,3,03:00:00
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8,2023-03-01,4,04:00:00

## Step 5 : Numpy Matrix Exercises

Convert relevant DataFrame columns into Numpy arrays and perform matrix operations 

Extract temperature and wind_speed as numpy arrays

## a) : Reshape into matrix form

Assume each row is a day

Reshape temperature into a (10,24) matrix

Calculate daily min, max, mean across rows

In [23]:
# Extract temperature and wind as Numpy arrays
import numpy as np

temp = df['temperature_C'].to_numpy()
wind = df['wind_speed_kmph'].to_numpy()

In [24]:
# Reshaping temperature into a 10,24 matrix

temp_matrix = temp.reshape((10,24))

# function for finding min : 
def min() :
    return temp_matrix.min()

# function for finding max : 
def max() :
    return temp_matrix.max()

# function for finding min : 
def mean() :
    return temp_matrix.mean()


print(f'Minimum value for temp col : {min()}')    
print(f'Maximum value for temp col : {max()}')    
print(f'Mean value for temp col : {mean()}')

Minimum value for temp col : 11.5
Maximum value for temp col : 28.7
Mean value for temp col : 21.389583333333334

### b) Normalize the temperature matrix
- Subtract the mean and divide by std deviation
- Do it manually using NumPy functions

In [44]:
# Finding the mean of the whole temp_matrix

mean_temp_matrix = np.mean(temp_matrix)
mean_temp_matrix

np.float64(21.389583333333334)

In [91]:
# Finding the std deviation of temp_matrix

std_temp_matrix = np.std(temp_matrix)
std_temp_matrix

np.float64(3.4462201264170895)

In [92]:
# Take every value one-by-one from the matrix and then subtract it from mean and then divide by std deviation. 

normalized_matrix = (temp_matrix - mean_temp_matrix) / std_temp_matrix
print(normalized_matrix)

[[-1.38980772 -1.50587692 -1.76703261 -1.62194611 -0.14206386 -0.17108116
   0.40926482  0.32221292 -0.05501196  1.97619897  1.97619897  1.2217492
   1.1637146   0.58336862  1.80209518  0.69943781  0.17712643  0.67042051
   0.49631672  0.20614373 -0.92553093 -0.57732335 -0.49027145 -1.9411364 ]
 [-1.59292881 -1.65096341 -1.09963473 -0.40321955  0.17712643 -0.05501196
   0.38024752  0.03203993  0.64140321  2.12128547 -0.25813306  1.0766627
   0.20614373  0.90255891  0.35123022  0.14810913  0.72845511  0.72845511
   0.81550701  0.17712643 -0.43223685 -0.75142714 -1.41882502 -0.98356553]
 [-2.26032669 -1.65096341 -0.83847904 -1.59292881  1.25076649 -0.14206386
  -0.17108116 -0.20009846  0.26417833  1.25076649  0.9896108  -0.05501196
   1.1927319   0.14810913  0.29319563  0.9605935   0.87354161  0.87354161
   0.55435132  0.87354161  0.38024752 -0.14206386 -0.80946174 -1.73801531]
 [-1.36079042 -0.78044444 -1.01258283 -1.56391151  0.03203993  0.20614373
   1.65700868  0.67042051  0.14810913  0.81550701  1.56995678  0.87354161
   0.87354161  1.25076649  0.75747241 -0.54830605  0.46729942  0.67042051
  -0.46125415 -0.08402926 -0.78044444 -0.17108116 -0.49027145 -1.59292881]
 [-0.49027145 -2.60853428 -0.78044444 -0.72240984 -0.05501196 -0.11304656
  -0.51928875 -0.25813306  0.9605935   0.9605935   0.55435132  0.49631672
   0.40926482  0.90255891  1.0186281   0.9605935   0.78648971  0.32221292
   0.81550701  0.55435132  0.23516103  0.72845511 -1.33177312 -0.86749634]
 [-1.04160013 -0.83847904 -0.08402926  0.14810913 -1.01258283 -1.38980772
   0.55435132  0.9896108   0.32221292  1.33781839  1.1637146   0.84452431
   1.39585299 -0.17108116 -0.02599466  0.38024752  0.9605935   0.61238592
   1.2217492   0.52533402  0.72845511 -1.70899801 -0.46125415 -1.18668663]
 [-1.62194611 -1.09963473 -1.01258283 -1.01258283 -0.46125415  0.58336862
  -0.43223685  1.25076649  0.49631672  1.30880109  0.87354161  0.32221292
   0.9896108   0.90255891  0.81550701  0.43828212 -0.40321955 -0.20009846
  -0.25813306  0.14810913  0.52533402 -1.73801531 -1.76703261 -1.09963473]
 [-2.28934399 -2.28934399 -1.15766933 -1.9121191  -0.05501196 -0.83847904
   0.06105723  0.58336862  1.33781839  0.26417833  0.26417833  1.0186281
   0.67042051  0.67042051  0.9315762   0.64140321  1.1927319   0.87354161
   0.32221292  0.03203993 -0.69339254 -1.18668663 -1.79604991 -1.01258283]
 [-2.0572056  -1.18668663 -1.67998071  0.03203993 -1.04160013 -0.05501196
  -0.22911576 -0.02599466  0.40926482 -0.05501196  1.0766627   1.25076649
   1.65700868  1.0476454   1.0476454   0.67042051  0.03203993  0.84452431
   0.64140321 -0.80946174 -0.51928875 -1.9411364  -0.69339254 -1.50587692]
 [-1.07061743 -1.47685962 -1.33177312 -1.18668663 -0.40321955  0.11909183
   0.55435132  0.87354161  0.78648971  2.06325087  1.27978379  1.1346973
   1.1346973   0.67042051  0.75747241  0.38024752  0.81550701  0.35123022
  -0.05501196  0.58336862 -0.34518495 -0.34518495 -0.14206386 -2.86968997]]

### c) Apply custom mask/filter
- Create a mask for wind speed > 15 kmph
- Use it to extract high-wind readings

In [101]:
# Step 1: Create the mask
wind_mask = wind > 15
print(wind_mask)

[False False False False False False False False False False False  True
  True  True False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False  True  True  True
  True False False  True  True False False False False False False False
 False False False False False False False False False False False  True
  True False False False False False False False False False False False
 False False False False False False False False False  True False  True
  True False  True False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
  True  True False False False False False False False False False False
 False False False False False False False False False  True  True False
 False  True False False  True False False False False False False False
 False False False False False False False False False False  True  True
  True  True False False False False False False False False False False]

In [102]:
# Step 2: Apply the mask to extract high wind readings
high_wind_readings = wind[wind_mask]
print(high_wind_readings)

[17.6 16.  16.5 16.3 16.7 15.8 17.8 15.1 16.3 15.2 17.  15.9 15.6 15.8
 15.4 15.6 16.3 15.3 16.2 16.9 15.3 15.2 15.5 17.4 17.4 15.4 15.4 16.5
 17.  15.7]

## Final Challenge: Write Your Own Function
Write a function `daily_summary(matrix)` that takes a NumPy matrix of shape (10, 24) and returns a summary dictionary for each day.

In [161]:
def daily_summary(matrix) :
    summary_dict = []
    
    for i in matrix : 
        day_dict = {
            'mean' : i.mean(), 
            'max' : i.max(), 
            'min' : i.min() 
        }

        summary_dict.append(day_dict)
    return summary_dict
    
summaries = daily_summary(temp_matrix)

In [169]:
for day, summary in enumerate(summaries, 1) : 
    print(f'Day : {day}, Mean : {summary['mean']:.2f}, Max : {summary['max']:.2f}, Min : {summary['min']:.2f}')

Day : 1, Mean : 21.55, Max : 28.20, Min : 14.70
Day : 2, Mean : 21.37, Max : 28.70, Min : 15.70
Day : 3, Mean : 21.43, Max : 25.70, Min : 13.60
Day : 4, Mean : 21.55, Max : 27.10, Min : 15.90
Day : 5, Mean : 21.67, Max : 24.90, Min : 12.40
Day : 6, Mean : 21.86, Max : 26.20, Min : 15.50
Day : 7, Mean : 21.04, Max : 25.90, Min : 15.30
Day : 8, Mean : 20.76, Max : 26.00, Min : 13.50
Day : 9, Mean : 20.95, Max : 27.10, Min : 14.30
Day : 10, Mean : 21.72, Max : 28.50, Min : 11.50